name: pokedex
description: A Dart wrapper for PokeAPI that provides everything Pokémon-related.
version: 0.1.0
repository: https://github.com/galatea21/dart_pokedex

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    freezed_annotation: ^1.1.0
    http: ^0.13.4
    json_annotation: ^4.4.0

dev_dependencies:
    build_runner: ^2.1.7
    freezed: ^1.1.1
    json_serializable: ^6.1.4
    lint: ^1.8.2
    test: ^1.20.1
