name: pokedex
description: A Dart wrapper for PokeAPI that provides everything Pokémon-related.
version: 0.2.0
repository: https://github.com/galatea21/dart_pokedex

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    freezed_annotation: ^2.4.1
    http: ^0.13.6
    json_annotation: ^4.8.1

dev_dependencies:
    build_runner: ^2.4.6
    freezed: ^2.4.2
    json_serializable: ^6.7.1
    lints: ^2.1.1
    test: ^1.24.5
