name: pokedex
description: A Dart wrapper for PokeAPI that provides everything Pokémon-related.
version: 0.2.0
repository: https://github.com/galatea21/dart_pokedex

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    freezed_annotation: ^2.1.0
    http: ^0.13.5
    json_annotation: ^4.7.0

dev_dependencies:
    build_runner: ^2.2.1
    freezed: ^2.1.1
    json_serializable: ^6.4.1
    lints: ^2.0.0
    test: ^1.21.6
