name: poke_dart
description: A Dart wrapper for Pokemon API that provides everything Pokemon-related.
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  freezed: ^0.14.5
  freezed_annotation: ^0.14.3
  http: ^0.13.3
  json_annotation: ^4.1.0
  json_serializable: ^5.0.1
  path: ^1.8.0

dev_dependencies:
  build_runner:
  lints: ^1.0.0
  test: ^1.16.0
