name: poke_dart
description: A Dart wrapper for Pokemon API that provides everything Pokemon-related.
version: 1.0.0

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    freezed_annotation: ^1.0.0
    http: ^0.13.4
    json_annotation: ^4.3.0
    json_serializable: ^6.0.1
    path: ^1.8.0

dev_dependencies:
    build_runner: ^2.1.5
    freezed: ^1.0.0
    lints: ^1.0.1
    test: ^1.19.4
